version: "3.8"

services:
  db:
    container_name: mysqldb
    image: mysql
    hostname: dataserver
    environment:
      MYSQL_ROOT_PASSWORD: "senha123"
      MYSQL_DATABASE: "users_db"
    ports:
      - "3306:3306"

    volumes:
      - ./data:/var/lib/mysql
    networks:
      - minha-rede
  auth-api:
    container_name: authapi
    restart: always
    build:
      context: auth-api-backend
    volumes:
      - ./auth-api-backend:/usr/auth-api-backend
      - /usr/auth-api-backend/node_modules
    depends_on:
      - db
    environment:
      PORT: 5000
      
    networks:
      - minha-rede
    ports: 
      - "5000:5000"
networks:
   minha-rede:
     driver: bridge